services:
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app_network
      - shared_network

  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blogdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-vector-db.sql:/docker-entrypoint-initdb.d/init-vector-db.sql
    restart: unless-stopped
    networks:
      - app_network
      - shared_network

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '6000:6000'
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - app_network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
  shared_network:
    external: true
